# SSM package name for Otel Collector
ssm_package_name = "testAWSDistroOTel-Collector"

# Base64 value of Otel Collector YAML configuration
ssm_config = "CmV4dGVuc2lvbnM6CiAgaGVhbHRoX2NoZWNrOgogIHBwcm9mOgogICAgZW5kcG9pbnQ6IDAuMC4wLjA6MTc3NzcKCnJlY2VpdmVyczoKICBvdGxwOgogICAgcHJvdG9jb2xzOgogICAgICBncnBjOgogICAgICAgIGVuZHBvaW50OiAwLjAuMC4wOjQzMTcKCmV4cG9ydGVyczoKICBhd3N4cmF5OgogICAgcmVnaW9uOiAndXMtd2VzdC0yJwogIGF3c2VtZjoKICAgIHJlZ2lvbjogJ3VzLXdlc3QtMicKCnNlcnZpY2U6CiAgcGlwZWxpbmVzOgogICAgdHJhY2VzOgogICAgICByZWNlaXZlcnM6IFtvdGxwXQogICAgICBleHBvcnRlcnM6IFthd3N4cmF5XQogICAgbWV0cmljczoKICAgICAgcmVjZWl2ZXJzOiBbb3RscF0KICAgICAgZXhwb3J0ZXJzOiBbYXdzZW1mXQoKICBleHRlbnNpb25zOiBbcHByb2Zd"
# enable SSM package validation
enable_ssm_validate = true

# disable mocked server
disable_mocked_server = true

# enable SSM installation
install_package_source = "ssm"
