# SSM package name for Otel Collector
ssm_package_name = "testAWSDistroOTel-Collector"

# Base64 value of Otel Collector YAML configuration
ssm_config = "CmV4dGVuc2lvbnM6CiAgaGVhbHRoX2NoZWNrOgogIHBwcm9mOgogICAgZW5kcG9pbnQ6IDAuMC4wLjA6MTc3NzcKCnJlY2VpdmVyczoKICBvdGxwOgogICAgcHJvdG9jb2xzOgogICAgICBncnBjOgogICAgICAgIGVuZHBvaW50OiAwLjAuMC4wOjQzMTcKCnByb2Nlc3NvcnM6CiAgYmF0Y2g6CgpleHBvcnRlcnM6CiAgYXdzeHJheToKICAgIHJlZ2lvbjogJ3VzLXdlc3QtMicKICBhd3NlbWY6CiAgICByZWdpb246ICd1cy13ZXN0LTInCgpzZXJ2aWNlOgogIHBpcGVsaW5lczoKICAgIHRyYWNlczoKICAgICAgcmVjZWl2ZXJzOiBbb3RscF0KICAgICAgZXhwb3J0ZXJzOiBbYXdzeHJheV0KICAgIG1ldHJpY3M6CiAgICAgIHJlY2VpdmVyczogW290bHBdCiAgICAgIGV4cG9ydGVyczogW2F3c2VtZl0KCiAgZXh0ZW5zaW9uczogW3Bwcm9mXQ=="
# enable SSM package validation
enable_ssm_validate = true

# disable mocked server
disable_mocked_server = true

# enable SSM installation
install_package_source = "ssm"
